/**
 * Code-defined permission catalog. Role → permission assignments live in DB.
 */
export const PERMISSIONS = [
  "users.manage",
  "clients.manage",
  "clients.delete",
  "clients.view",
  "reports.export",
  "analytics.view",
  "tasks.manage",
  "tasks.assign",
  "gates.manage",
  "gates.close",
  "risks.manage",
  "comms.manage",
  "api_keys.manage",
  "settings.manage",
  "roles.manage",
  "audit.view",
  "comments.create",
  "comments.moderate",
  "files.upload",
  "files.manage",
  "invitations.manage",
  "notifications.view",
  "views.manage",
  "custom_fields.manage",
  "automations.manage",
  "users.impersonate",
  "billing.view",
  "flags.manage",
  "webhooks.manage",
  "ai.use",
  "imports.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export function isPermission(value: string): value is Permission {
  return (PERMISSIONS as readonly string[]).includes(value);
}

export const PERMISSION_LABELS: Record<Permission, string> = {
  "users.manage": "Manage Users",
  "clients.manage": "Manage Clients",
  "clients.delete": "Delete Clients",
  "clients.view": "View Clients",
  "reports.export": "Export Reports",
  "analytics.view": "View Analytics",
  "tasks.manage": "Manage Tasks",
  "tasks.assign": "Assign Tasks",
  "gates.manage": "Manage Gates",
  "gates.close": "Close Launch Gates",
  "risks.manage": "Manage Risks",
  "comms.manage": "Manage Comms",
  "api_keys.manage": "Manage API Keys",
  "settings.manage": "Organization Settings",
  "roles.manage": "Manage Roles",
  "audit.view": "View Audit Log",
  "comments.create": "Create Comments",
  "comments.moderate": "Moderate Comments",
  "files.upload": "Upload Files",
  "files.manage": "Manage Files",
  "invitations.manage": "Manage Invitations",
  "notifications.view": "View Notifications",
  "views.manage": "Manage Saved Views",
  "custom_fields.manage": "Manage Custom Fields",
  "automations.manage": "Manage Automations",
  "users.impersonate": "Impersonate Users",
  "billing.view": "View Billing",
  "flags.manage": "Manage Feature Flags",
  "webhooks.manage": "Manage Webhooks",
  "ai.use": "Use AI Assistant",
  "imports.manage": "Import / Export Data",
};

/** System role slugs and default permission grants */
export const SYSTEM_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  superadmin: [...PERMISSIONS],
  ceo: [
    "users.manage",
    "clients.manage",
    "clients.delete",
    "clients.view",
    "reports.export",
    "analytics.view",
    "tasks.manage",
    "tasks.assign",
    "gates.manage",
    "gates.close",
    "risks.manage",
    "comms.manage",
    "api_keys.manage",
    "settings.manage",
    "roles.manage",
    "audit.view",
    "comments.create",
    "comments.moderate",
    "files.upload",
    "files.manage",
    "invitations.manage",
    "notifications.view",
    "views.manage",
    "custom_fields.manage",
    "automations.manage",
    "users.impersonate",
    "billing.view",
    "flags.manage",
    "webhooks.manage",
    "ai.use",
    "imports.manage",
  ],
  ae: [
    "clients.manage",
    "clients.view",
    "analytics.view",
    "tasks.manage",
    "tasks.assign",
    "gates.manage",
    "gates.close",
    "risks.manage",
    "comms.manage",
    "comments.create",
    "files.upload",
    "notifications.view",
    "views.manage",
    "ai.use",
  ],
  viewer: [
    "clients.view",
    "analytics.view",
    "notifications.view",
    "billing.view",
  ],
};

export const SYSTEM_ROLES = [
  { slug: "superadmin", name: "Super Admin" },
  { slug: "ceo", name: "CEO" },
  { slug: "ae", name: "Account Executive" },
  { slug: "viewer", name: "Viewer" },
] as const;
