import type {
  AccountExecutive,
  AeId,
  Client,
  Comm,
  FollowUp,
  Risk,
  Task,
} from "./types";

export const ACCOUNT_EXECUTIVES: Record<AeId, AccountExecutive> = {
  maya: { id: "maya", name: "Maya Chen", initials: "MC", capacityLoad: 80 },
  devon: { id: "devon", name: "Devon Ray", initials: "DR", capacityLoad: 93 },
  priya: { id: "priya", name: "Priya Nair", initials: "PN", capacityLoad: 53 },
};

/** Seed clients — field values from VirtualClinicOS-2.html */
export const CLIENTS: Client[] = [
  {
    id: 1,
    name: "Meridian Men's Health",
    aeId: "maya",
    phase: 6,
    status: "Active",
    health: "green",
    daysToLaunch: 24,
    mrr: 2400,
    waitingOn: "Nothing",
    waitDays: 0,
    criticalOverdue: 0,
  },
  {
    id: 2,
    name: "Coastal Wellness Rx",
    aeId: "devon",
    phase: 4,
    status: "Active",
    health: "yellow",
    daysToLaunch: 41,
    mrr: 1800,
    waitingOn: "Client",
    waitDays: 6,
    criticalOverdue: 0,
  },
  {
    id: 3,
    name: "Vitality Peptides",
    aeId: "maya",
    phase: 8,
    status: "Active",
    health: "red",
    daysToLaunch: 5,
    mrr: 3200,
    waitingOn: "Internal",
    waitDays: 2,
    criticalOverdue: 1,
  },
  {
    id: 4,
    name: "Restore Hormone Clinic",
    aeId: "priya",
    phase: 2,
    status: "Active",
    health: "red",
    daysToLaunch: 55,
    mrr: 1500,
    waitingOn: "Client",
    waitDays: 12,
    criticalOverdue: 0,
  },
  {
    id: 5,
    name: "Apex TRT",
    aeId: "devon",
    phase: 10,
    status: "Active",
    health: "green",
    daysToLaunch: 2,
    mrr: 2900,
    waitingOn: "Nothing",
    waitDays: 0,
    criticalOverdue: 0,
  },
  {
    id: 6,
    name: "Lumen Skin & Aesthetics",
    aeId: "priya",
    phase: 5,
    status: "Active",
    health: "yellow",
    daysToLaunch: 33,
    mrr: 2100,
    waitingOn: "Nothing",
    waitDays: 0,
    criticalOverdue: 0,
  },
  {
    id: 7,
    name: "NovaCare Telehealth",
    aeId: "maya",
    phase: 3,
    status: "Active",
    health: "green",
    daysToLaunch: 60,
    mrr: 1200,
    waitingOn: "Client",
    waitDays: 3,
    criticalOverdue: 0,
  },
  {
    id: 8,
    name: "Elevate Weight Mgmt",
    aeId: "devon",
    phase: 11,
    status: "Hypercare",
    health: "green",
    daysToLaunch: -8,
    mrr: 3500,
    waitingOn: "Nothing",
    waitDays: 0,
    criticalOverdue: 0,
  },
];

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "QA — Checkout flow failing",
    clientId: 3,
    priority: "Urgent",
    status: "In Progress",
    owner: "QA Team",
    due: "Today",
  },
  {
    id: "t2",
    title: "SSL certificate final check",
    clientId: 5,
    priority: "High",
    status: "To Do",
    owner: "Dev",
    due: "Tomorrow",
  },
  {
    id: "t3",
    title: "Chase missing brand assets",
    clientId: 4,
    priority: "High",
    status: "Blocked",
    owner: "Maya Chen",
    due: "Overdue 3d",
  },
  {
    id: "t4",
    title: "Payment gateway live cutover",
    clientId: 3,
    priority: "Urgent",
    status: "Blocked",
    owner: "Dev",
    due: "In 4d",
  },
  {
    id: "t5",
    title: "Mockups v2 — client feedback",
    clientId: 2,
    priority: "Medium",
    status: "In Review",
    owner: "Design",
    due: "In 2d",
  },
  {
    id: "t6",
    title: "Provision company email",
    clientId: 7,
    priority: "Medium",
    status: "In Progress",
    owner: "Ops",
    due: "In 5d",
  },
  {
    id: "t7",
    title: "Confirm launch date & war room",
    clientId: 5,
    priority: "High",
    status: "To Do",
    owner: "Devon Ray",
    due: "Tomorrow",
  },
  {
    id: "t8",
    title: "Booking flow QA — mobile",
    clientId: 3,
    priority: "High",
    status: "In Review",
    owner: "QA Team",
    due: "In 1d",
  },
  {
    id: "t9",
    title: "LegitScript submission packet",
    clientId: 4,
    priority: "Medium",
    status: "To Do",
    owner: "Compliance",
    due: "In 6d",
  },
  {
    id: "t10",
    title: "Training session — go-live",
    clientId: 5,
    priority: "Medium",
    status: "Done",
    owner: "Client Success",
    due: "Done",
  },
  {
    id: "t11",
    title: "Hypercare handover doc",
    clientId: 8,
    priority: "Low",
    status: "Done",
    owner: "Maya Chen",
    due: "Done",
  },
  {
    id: "t12",
    title: "Treatment options config",
    clientId: 1,
    priority: "Medium",
    status: "In Progress",
    owner: "Dev",
    due: "In 3d",
  },
];

export const RISKS: Risk[] = [
  {
    id: "r1",
    clientId: 3,
    title: "Launch-blocking QA failures in checkout",
    type: "Issue",
    severity: "Critical",
    status: "Open",
  },
  {
    id: "r2",
    clientId: 3,
    title: "Client asset delays threatening timeline",
    type: "Risk",
    severity: "High",
    status: "Mitigating",
  },
  {
    id: "r3",
    clientId: 4,
    title: "Brand kit blocking onboarding milestones",
    type: "Risk",
    severity: "Critical",
    status: "Open",
  },
  {
    id: "r4",
    clientId: 2,
    title: "Client review turnaround slowing schedule",
    type: "Risk",
    severity: "Medium",
    status: "Mitigating",
  },
];

export const FOLLOW_UPS: FollowUp[] = [
  {
    id: "f1",
    clientId: 7,
    note: "Confirm hosting credentials",
    due: "Today",
    tone: "urgent",
  },
  {
    id: "f2",
    clientId: 3,
    note: "QA status → send recap",
    due: "Tomorrow",
    tone: "warn",
  },
  {
    id: "f3",
    clientId: 1,
    note: "Weekly check-in",
    due: "In 4d",
    tone: "ok",
  },
];

export const COMMS: Comm[] = [
  {
    id: "c1",
    clientId: 3,
    subject: "QA failure recap — checkout",
    when: "2h ago",
    channel: "Slack",
  },
  {
    id: "c2",
    clientId: 3,
    subject: "Launch readiness call notes",
    when: "Yesterday",
    channel: "Call",
  },
  {
    id: "c3",
    clientId: 3,
    subject: "Payment gateway cutover plan",
    when: "2d ago",
    channel: "Email",
  },
];

export const CURRENT_USER = {
  name: "Alex Rivera",
  initials: "AR",
  role: "CEO · Command Center",
} as const;
